stages: [build]

build:
  stage: build
  image: node:22-bookworm
  script:
    - npm ci
    - npm run build -w apps/api
    - npm run build -w apps/web
  artifacts:
    when: on_success
    paths:
      - apps/api/dist/
      - apps/web/.next/
